Dev
DanisHaertdinov/Pomodoro-nodeJs pull request #1
Opened 2021-07-05 17:04 UTC by DanisHaertdinov

2021-07-28 20:01 UTC, kicumkicum requested changes
Ну ништяк! Дело прям пошло💪

2021-07-28 20:01 UTC, kicumkicum commented on index.js
> +const timer = (duration, callback, command) => {
Функцию стоит называть с глагола. Чтобы понимать, что там происходит

2021-07-28 20:01 UTC, kicumkicum commented on index.js
>      }
Точка с запятой, как водится)

2021-07-28 20:01 UTC, kicumkicum commented on index.js
> +
Лишняя пустота

2021-07-28 20:01 UTC, kicumkicum commented on index.js
> +                    console.log(`prepare to new challenge`);
Давай вынесем в ишью создать сущность для отправки сообщений, чтобы не использовать console.log напрямую. Это не приоритетная задача, но она позволит проще отличать сообщения от логов

2021-07-28 20:01 UTC, kicumkicum commented on index.js
> +const timer = (duration, callback, command) => {
callback лучше передавать или первым, или последним (лучше последним). А когда разбиваешь аргументы, то какие-то можно упустить из виду

2021-07-28 20:01 UTC, kicumkicum commented on index.js
> +                callback();
А тут не надо обнюлять timerId?

2021-07-28 20:01 UTC, kicumkicum commented on index.js
>  const WORK_TIME = 50000;
Лучше время через умножение на 1000 делать. Так проще воспринимать секунды. Да и нули легче считать

2021-08-04 15:48 UTC, DanisHaertdinov commented on index.js
>  const WORK_TIME = 50000;
done

2021-08-04 15:48 UTC, DanisHaertdinov commented on index.js
> +                callback();
done

2021-08-04 15:48 UTC, DanisHaertdinov commented on index.js
> +
done

2021-08-04 15:48 UTC, DanisHaertdinov commented on index.js
>      }
done

2021-08-04 15:53 UTC, DanisHaertdinov commented on index.js
> +const timer = (duration, callback, command) => {
done

2021-08-04 15:55 UTC, DanisHaertdinov commented on index.js
> +                    console.log(`prepare to new challenge`);
done

2021-08-09 09:53 UTC, kicumkicum approved these changes

2021-08-09 09:53 UTC, merged