Sprint 1
DanisHaertdinov/Pomodoro-nodeJs pull request #13
Opened 2021-10-12 21:28 UTC by DanisHaertdinov

2021-10-13 07:47 UTC, kicumkicum approved these changes
Бодро начал 🔥

2021-10-13 07:47 UTC, kicumkicum commented on package.json
> +    "@babel/core": "7.15.8",
А babel нужен только для eslint? Больше не для чего?

2021-10-13 07:47 UTC, kicumkicum commented on index.js
> +  await timer.start(duration * 1000);
О, круто выглядит!

2021-10-13 22:54 UTC, DanisHaertdinov commented on package.json
> +    "@babel/core": "7.15.8",
Да, только для eslint

2021-10-14 15:40 UTC, kicumkicum requested changes
Нормально так понапилил. Обсудим, сольем, а потом уже можно и порефакторить

2021-10-14 15:40 UTC, kicumkicum commented on 6
> +  run `npm audit fix` to fix them, or `npm audit` for details
Это наверно лог какой-то попал

2021-10-14 15:40 UTC, kicumkicum commented on package.json
> +    "lint-staged": "^11.2.3",
Нужно будет переустановить эти пакеты с фиксированием зависимостей

2021-10-14 15:40 UTC, kicumkicum commented on package.json
> +    "prepare": "husky install"
По идее без этого можно обойтись. husky сам себя устанавливает, когда ты делаешь `npm install`

2021-10-14 15:40 UTC, kicumkicum commented on index.js
> +  await setRestTimer();
Нужно будет подумать над этими `set`. Расходятся ожидания и реальность

2021-10-28 17:22 UTC, kicumkicum commented on index.js
> +  await setRestTimer();
Оставим до рефакторинга

2021-11-15 08:25 UTC, kicumkicum commented on timer.js
> +  #timerId = null;
FYI С нативными приватными свойствами не все так однозначно. Я не могу увидеть пользу в них для обычного кода, кроме как сложность отладки. Когда приватные свойства имеют просто метку `_`, то при отладке ты можешь спокойно к ним обращаться в рантайме и читать. 

А с нативными так не получится. И получается, что жизнь становится сложнее.

Это просто сообщение-размышление. Код править не нужно, но нужно поразмышлять об этом)

2021-11-15 08:26 UTC, kicumkicum approved these changes
👍🏽

2021-11-15 08:26 UTC, merged