add sound play feature
DanisHaertdinov/Pomodoro-nodeJs pull request #7
Opened 2021-09-08 15:59 UTC by DanisHaertdinov

2021-09-08 16:16 UTC, DanisHaertdinov commented
Забыл запулить перед коммитом, хороший повод попрактиковаться с конфликтами)

2021-09-10 15:45 UTC, kicumkicum requested changes
💪🏽 🍄 🚀

2021-09-10 15:45 UTC, kicumkicum commented on index.js
> +}
Надо разобраться с `;`. Их острая нехватка

2021-09-10 15:45 UTC, kicumkicum commented on index.js
> +const WORK_TIME = 5000;
Лучше сразу с разрядностью. `1000 * 5` или `5 * 1000`. Написав один раз, читать и править будет проще

2021-09-10 15:45 UTC, kicumkicum commented on index.js
> +            timerId = setTimer(WORK_TIME,`get rest`, SOUND_URL)
Ну а тут упущен пробел после `,`. Давай затащим приттиер или линтер на прекоммит и решим эту проблему

2021-09-10 15:45 UTC, kicumkicum commented on index.js
> +            timerId = setTimer(WORK_TIME,`get rest`, SOUND_URL)
Немного странно, что для установки таймера нужно передать сообщение и звук. Но возможно я просто думаю не о том таймере. Это не таймер setTimeout, а таймер приложения. Но к этому приходишь не сразу.

Можно добавить больше конкретики, например, `setPomodoro(time, message, sound)`. И тогда мысль двигается в нужном направлении.

2021-09-10 15:45 UTC, kicumkicum commented on index.js
> +    playSound(SOUND_URL)
Тонкий момент - не стоит запускать неконтролируемо промисы. Это усложняет понимание кода (нужно держать в памяти, что есть промис, который выполняется в непроизвольный момент), порождает баги (по той же причине).

Если есть промис, то он должен быть под контролем. То есть, в случае обычной функции - она должна вернуть промис. В случае асинхронной функции, нужно сделать `await`.

Если все таки нужен неконтролируемый промис, то стоит об этом сообщить комментом.

2021-09-10 15:45 UTC, kicumkicum commented on package.json
> +    "stupid-player": "0.4.0"
Можно обновиться))

2021-09-10 15:45 UTC, kicumkicum commented on index.js
> +const SOUND_URL = 'http://soundfxcenter.com/video-games/street-fighter/8d82b5_Street_Fighter_Coin_Sound_Effect.mp3'
Можно поменять на локальный))

2021-09-16 16:55 UTC, kicumkicum requested changes
Крутяг! Идём вперёд. Только немного порезолвить комменты

2021-09-16 16:55 UTC, kicumkicum commented on index.js
> +
Много пустых строк

2021-09-16 16:55 UTC, kicumkicum commented on index.js
> +    setTimeout(() => {
Давай переделаем setTimeout на промисы. В ноде кажется у них есть метод для этого.

Это нужно для того, чтобы код стал линейным и более простым для восприятия

2021-09-16 16:55 UTC, kicumkicum commented on index.js
>              setTimer(
Этот тайм-аут тоже давай на промисы

2021-09-16 16:55 UTC, kicumkicum commented on package.json
> +    "stupid-player": "0.4.1"
Можно обновлять на 0.4.2. Я попробовал, работает даже))

2021-09-16 16:55 UTC, kicumkicum commented on index.js
> +    const player = new StupidPlayer();
Он многоразовый. Достаточно держать один инстанст для всего приложения

2021-09-16 17:21 UTC, kicumkicum requested changes
Крутяг! Идём вперёд. Только немного порезолвить комменты

2021-10-06 14:25 UTC, DanisHaertdinov commented on index.js
> +const WORK_TIME = 5000;
done

2021-10-06 14:26 UTC, DanisHaertdinov commented on index.js
> +    const player = new StupidPlayer();
done

2021-10-06 14:26 UTC, DanisHaertdinov commented on package.json
> +    "stupid-player": "0.4.1"
done

2021-10-06 14:30 UTC, DanisHaertdinov commented on index.js
> +    setTimeout(() => {
Асинхронные таймауты доступный с 15 версии. Может сделаем свою обёртку над setTimeout?

2021-10-06 14:31 UTC, DanisHaertdinov commented on index.js
> +
done

2021-10-06 15:59 UTC, kicumkicum commented on index.js
> +    setTimeout(() => {
Да, отлично!

2021-10-06 16:59 UTC, kicumkicum commented on index.js
> +    setTimeout(() => {
Создал #12

2021-10-06 16:59 UTC, kicumkicum approved these changes

2021-10-06 16:59 UTC, merged